ai:
  # preferred provider for ChatModel selection in AiConfig: 'ollama', 'google' or 'openai'
  provider: openai

spring:
  application:
    name: loganalyser
  config:
    import: "optional:file:.env[.properties]"
  ai:
    chat:
      client:
        enabled: false
    ollama:
      enabled: false
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma:2b
    google:
      genai:
        enabled: false
        api-key: ${GOOGLE_API_KEY}
    openai:
      api-key: ${OPENAI_API_KEY:${OPEN_API_KEY:}}
      base-url: https://aicafe.hcl.com/AICafeService/api/v1/subscription
      chat:
        enabled: true
        completions-path: /openai/deployments/gpt-4.1/chat/completions?api-version=2024-12-01-preview
        options:
          model: gpt-4.1-mini
          temperature: 0.1
          http-headers:
            api-key: ${OPENAI_API_KEY:${OPEN_API_KEY:}}
      retry:
        max-attempts: 3

log:
  env-urls:
    dev: "http://dev-logs.example.com"
    test: "http://test-logs.example.com"
    acc: "http://acc-logs.example.com"
    prd: "http://prd-logs.example.com"

